### ISSUE TITLE
TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by mishushakov** [e2b-dev/desktop#2]
```
Traceback (most recent call last):
  File "/Users/mish/Documents/Playground/claude-computer/hello.py", line 1, in <module>
    from e2b_desktop import Sandbox
  File "/Users/mish/Documents/Playground/claude-computer/.venv/lib/python3.9/site-packages/e2b_desktop/__init__.py", line 3, in <module>
    from .main import Sandbox
  File "/Users/mish/Documents/Playground/claude-computer/.venv/lib/python3.9/site-packages/e2b_desktop/main.py", line 10, in <module>
    class Sandbox(SandboxBase):
  File "/Users/mish/Documents/Playground/claude-computer/.venv/lib/python3.9/site-packages/e2b_desktop/main.py", line 74, in Sandbox
    def locate_on_screen(self, text: str) -> tuple[int, int] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```

code in question:

```python
def locate_on_screen(self, text: str) -> tuple[int, int] | None:
```

**Comment by jakubno** [comment]
This method isn't present anymore
